GRAD_RATE_MASTER:
  Run: True
  Environment: "qa"
  Source:
    platform: "Smartsheet"
    sheet name: "Grad Rate Master"
    sheet id: "8065621301716868"
  Target:
    platform: "Snowflake"
    database: "DATALAKE_QA"
    schema: "SMARTSHEET_CF01"
    table: "GRAD_RATE_MASTER"
  Load Type: "Full Load"
