TEST_TABLE:
  Run: True
  Environment: "dev"
  Source:
    platform: "Postgres"
    database: "testdb"
    schema: "testschema"
    table: "testtable"
    audit_cols: ["created_date","modified_date"]
  Target:
    platform: "Snowflake"
    database: "TEST_DB"
    schema: "TEST_SCHEMA"
    table: "TEST_TABLE"
  Load Type: "Full Load"
