TABLE_COMM_MESSAGE_BODY:
  Run: False
  Environment: "qa"
  Source:
    platform: "Postgres"
    database: "QACC2"
    schema: "CC2"
    table: "COMM_MESSAGE_BODY"
    audit_cols: ["createdate"]
  Target:
    table: "COMM_MESSAGE_BODY"
  Load Type:
    load_type: "Full Load" # Full, Partial, or Incremental Load
TEST_TABLE:
  Run: True
  Environment: "dev"
  Source:
    platform: "Postgres"
    database: "testdb"
    schema: "testschema"
    table: "testtable"
    audit_cols: ["created_date","modified_date"]
  Target:
    platform: "Snowflake"
    database: "TEST_DB"
    schema: "TEST_SCHEMA"
    table: "TEST_TABLE"